config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :institutes
  resources :sites
  root   'static_pages#home'
  get    '/help', to: 'static_pages#help'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  get    'matching_start', to: 'static_pages#matching_start'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  The creators of this application are Emelie Dümpelmann and Rabea Schulze.
</p>

<p><strong>Emelie Dümpelmann</strong></p>

<p><strong>Rabea Schulze</strong></p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact</h1>
<p>
  Contact the Ruby on Rails Tutorial about the sample app at the
  <a href="http://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to the Matching App</h1>
  <h2><strong>Description:</strong></h2>
  <h3>
    This is the home page for a matching application. The intention is to allocate Bachelor
    students who are close to write their bachelor thesis to existing institutes of the underlying university.
    The application should provide an optimal solution so that the sorrow of the students is as small as possible.
  </h3>
  <%=image_tag("Matching.png", alt: "Matching", src:"app/assets/images/Matching.png") %>
  <br>
  <br>
  <br>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/static_pages/matching_start.html.erb
<% provide(:title, 'Zuordnung') %>
    <% if logged_in? %>


<h1>Das Zuordnungsproblem von Studenten zu Instituten</h1>
<p>
  Auf dieser Seite startet die Zuordnung!    <br>     <br>
  <%= link_to "Hier geht es zur Verwaltung der Studenten!", students_path %><br>
  <%= link_to "Hier geht es zur Verwaltung der Institute!", institutes_path %><br>
  <%= link_to "Hier geht es zur Verwaltung des GAMS-Pfades!", '#gams_path' %><br>
</p>

<br>

<% end %>