config/routes.rb
Rails.application.routes.draw do
  resources :students
  resources :institutes
  resources :sites
  root   'static_pages#home'
  get    '/help', to: 'static_pages#help'
  get    '/about', to: 'static_pages#about'
  get    '/contact', to: 'static_pages#contact'
  get    '/signup', to: 'users#new'
  get    '/login', to: 'sessions#new'
  get    'matching_start', to: 'static_pages#matching_start'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/institute.rb
class Institute < ApplicationRecord
end

app/controllers/institutes_controller.rb
class InstitutesController < ApplicationController
  before_action :set_institute, only: [:show, :edit, :update, :destroy]

  # GET /institutes
  # GET /institutes.json
  def index
    @institutes = Institute.all
  end

  # GET /institutes/1
  # GET /institutes/1.json
  def show
  end

  # GET /institutes/new
  def new
    @institute = Institute.new
  end

  # GET /institutes/1/edit
  def edit
  end

  # POST /institutes
  # POST /institutes.json
  def create
    @institute = Institute.new(institute_params)

    respond_to do |format|
      if @institute.save
        format.html { redirect_to @institute, notice: 'Institute was successfully created.' }
        format.json { render :show, status: :created, location: @institute }
      else
        format.html { render :new }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /institutes/1
  # PATCH/PUT /institutes/1.json
  def update
    respond_to do |format|
      if @institute.update(institute_params)
        format.html { redirect_to @institute, notice: 'Institute was successfully updated.' }
        format.json { render :show, status: :ok, location: @institute }
      else
        format.html { render :edit }
        format.json { render json: @institute.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /institutes/1
  # DELETE /institutes/1.json
  def destroy
    @institute.destroy
    respond_to do |format|
      format.html { redirect_to institutes_url, notice: 'Institute was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_institute
      @institute = Institute.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def institute_params
      params.require(:institute).permit(:name, :Anzahl_Professoren, :Anzahl_Mitarbeiter, :Betreuungsüberschusskapazität)
    end
end

app/helpers/institutes_helper.rb
module InstitutesHelper
end

app/views/institutes/_form.html.erb
<%= form_with(model: institute, local: true) do |form| %>
  <% if institute.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(institute.errors.count, "error") %> prohibited this institute from being saved:</h2>

      <ul>
      <% institute.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :institute_name %>
  </div>

  <div class="field">
    <%= form.label :Anzahl_Professoren %>
    <%= form.number_field :Anzahl_Professoren, id: :institute_Anzahl_Professoren %>
  </div>

  <div class="field">
    <%= form.label :Anzahl_Mitarbeiter %>
    <%= form.number_field :Anzahl_Mitarbeiter, id: :institute_Anzahl_Mitarbeiter %>
  </div>

  <div class="field">
    <%= form.label :Betreuungsüberschusskapazität %>
    <%= form.text_field :Betreuungsüberschusskapazität, id: :institute_Betreuungsüberschusskapazität %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/institutes/edit.html.erb
<h1>Editing Institute</h1>

<%= render 'form', institute: @institute %>

<%= link_to 'Show', @institute %> |
<%= link_to 'Back', institutes_path, "data-turbolinks": "false" %>

app/views/institutes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Institutes</h1>

<table  id="institutes" class="display">
  <thead>
    <tr>
      <th>Name</th>
      <th>Anzahl Professoren</th>
      <th>Anzahl Mitarbeiter</th>
      <th>Betreuungsüberschusskapazität</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @institutes.each do |institute| %>
      <tr>
        <td><%= best_in_place institute.itself, :name %></td>
        <td><%= institute.Anzahl_Professoren %></td>
        <td><%= institute.Anzahl_Mitarbeiter %></td>
        <td><%= institute.Betreuungsüberschusskapazität %></td>
        <td><%= link_to 'Show', institute %></td>
        <td><%= link_to 'Edit', edit_institute_path(institute) %></td>
        <td><%= link_to 'Destroy', institute, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Institute', new_institute_path %>
<br>
<%= link_to 'Back to Matching', matching_start_path %>

app/views/institutes/new.html.erb
<h1>New Institute</h1>

<%= render 'form', institute: @institute %>

<%= link_to 'Back', institutes_path, "data-turbolinks": "false" %>

app/views/institutes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= best_in_place @institute, :name %>
</p>

<p>
  <strong>Anzahl Professoren:</strong>
  <%= @institute.Anzahl_Professoren %>
</p>

<p>
  <strong>Anzahl Mitarbeiter:</strong>
  <%= @institute.Anzahl_Mitarbeiter %>
</p>

<p>
  <strong>Betreuungsüberschusskapazität:</strong>
  <%= @institute.Betreuungsüberschusskapazität %>
</p>

<%= link_to 'Edit', edit_institute_path(@institute) %> |
<%= link_to 'Back', institutes_path, "data-turbolinks": "false" %>